### ISSUE TITLE
I believe this should use OP_WRITE like out

### ISSUE THREAD

**Issue by cellux** [jnr/jnr-process#13]
https://github.com/jnr/jnr-process/blob/b7422d8cf62a60b693282c98ab462a89b981c712/src/main/java/jnr/process/Process.java#L33

**Comment by headius** [comment]
You are correct!

**Comment by headius** [comment]
Actually I realized the confusion here...

The "in" and "out" streams are described in terms of the *parent*, not the *child*. So "in" is actually the "out" from the child, and must be selectable for reading from the parent. "Out" is the "in" of the child and should be selectable for writing.

And following this logic, since "err" is another output from the child, it will be an input in the parent and should be selectable for reading.

I will add some tests to make this clear and also get a new release out with Java 9+ support (mostly just some module stuff).
